### ISSUE TITLE
ShaX Hirsiz Polis 80.93.220.82:7777

### ISSUE THREAD

**Issue by Shacous** [Hual/samp-discord-plugin#163] opened 2021-06-05 15:31 UTC
![shaxsky](https://user-images.githubusercontent.com/83518870/120896889-3b426600-c62c-11eb-82e1-d433af3fc820.png)
80.93.220.82:7777

**Comment by Heaaven** [comment] 2021-06-10 16:47
https://sampdiscord.fr

**Comment by AmyrAhmady** [comment] 2021-06-21 00:11
Duplicate of #156 , it has been added already.

**Closed by AmyrAhmady** 2021-06-21 00:11 UTC
